In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/sales_records.csv')

print(df.shape)       # e.g., (15420, 12)
print(df.dtypes)
print(df.head())
print(df.describe())
print(df.isnull().sum())
print(df.columns)

(500, 12)
Customer ID         str
order_id            str
order_date          str
Rev (USD)           str
region              str
status              str
notes               str
age             float64
month               str
product             str
sales_rep           str
country             str
dtype: object
  Customer ID   order_id  order_date Rev (USD)  region   status      notes  \
0     CUST1000  ORD05000  2025-05-21   2613.41   north   active  follow up
1     CUST1001  ORD05001  2025-11-05  20159.85    West   active  follow up
2     CUST1002  ORD05002  2025-03-21  29251.17   north  churned          -
3     CUST1003  ORD05003  2025-07-13  82728.28    East   active  follow up
4     CUST1004  ORD05004  2025-04-30  83751.22    East  churned  follow up

    age month     product sales_rep country
0  28.0   May       Basic     Alice     USA
1  63.0   Nov         Pro     Alice     USA
2  43.0   Mar         Pro     Alice  Canada
3  62.0   Jul  Enterprise     Alice     USA
4  51.0   Apr     Starter     Carol     USA
              age
count  444.000000
mean    44.398649
std     12.809107
min     22.000000
25%     33.000000
50%     44.000000
75%     56.000000
max     65.000000
Customer ID       0
order_id          0
order_date        0
Rev (USD)         0
region            0
status            0
notes           178
age              56
month             0
product           0
sales_rep         0
country           0
dtype: int64
Index(['Customer ID ', 'order_id', 'order_date', 'Rev (USD)', 'region',
       'status', 'notes', 'age', 'month', 'product', 'sales_rep', 'country'],
      dtype='str')

In [3]:
print(df.columns)

df.columns = ['_'.join(col.strip().lower().split(' ')).replace('(', '').replace(')', '') for col in df.columns.tolist()]
print(df.columns)

Index(['Customer ID ', 'order_id', 'order_date', 'Rev (USD)', 'region',
       'status', 'notes', 'age', 'month', 'product', 'sales_rep', 'country'],
      dtype='str')
Index(['customer_id', 'order_id', 'order_date', 'rev_usd', 'region', 'status',
       'notes', 'age', 'month', 'product', 'sales_rep', 'country'],
      dtype='str')

In [4]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df['rev_usd'] = pd.to_numeric(df['rev_usd'], errors='coerce')

df.head()

,customer_id,order_id,order_date,rev_usd,region,status,notes,age,month,product,sales_rep,country
0,CUST1000,ORD05000,2025-05-21,2613.41,north,active,follow up,28.0,May,Basic,Alice,USA
1,CUST1001,ORD05001,2025-11-05,20159.85,West,active,follow up,63.0,Nov,Pro,Alice,USA
2,CUST1002,ORD05002,2025-03-21,29251.17,north,churned,-,43.0,Mar,Pro,Alice,Canada
3,CUST1003,ORD05003,2025-07-13,82728.28,East,active,follow up,62.0,Jul,Enterprise,Alice,USA
4,CUST1004,ORD05004,2025-04-30,83751.22,East,churned,follow up,51.0,Apr,Starter,Carol,USA

In [5]:
revenue = df['rev_usd']
subset = df[['customer_id', 'rev_usd', 'region']]

print(revenue)
print(subset)

0       2613.41
1      20159.85
2      29251.17
3      82728.28
4      83751.22
         ...
495    46251.25
496    35287.95
497    19663.07
498    15317.86
499    17835.63
Name: rev_usd, Length: 500, dtype: float64
    customer_id   rev_usd  region
0      CUST1000   2613.41   north
1      CUST1001  20159.85    West
2      CUST1002  29251.17   north
3      CUST1003  82728.28    East
4      CUST1004  83751.22    East
..          ...       ...     ...
495    CUST1495  46251.25   North
496    CUST1496  35287.95    west
497    CUST1497  19663.07    west
498    CUST1498  15317.86   North
499    CUST1499  17835.63   NORTH

[500 rows x 3 columns]

In [6]:
high_value = df.loc[df['rev_usd'] > 10000, ['customer_id', 'rev_usd']]

high_value

    customer_id   rev_usd
1      CUST1001  20159.85
2      CUST1002  29251.17
3      CUST1003  82728.28
4      CUST1004  83751.22
5      CUST1005  14961.22
..          ...       ...
495    CUST1495  46251.25
496    CUST1496  35287.95
497    CUST1497  19663.07
498    CUST1498  15317.86
499    CUST1499  17835.63

[421 rows x 2 columns]

In [7]:
filtered = df[(df['region'] == 'North') & (df['rev_usd'] > 5000)]

filtered

,customer_id,order_id,order_date,rev_usd,region,status,notes,age,month,product,sales_rep,country
17,CUST1017,ORD05017,2025-05-02,82380.18,North,active,-,52.0,May,Basic,Carol,Canada
18,CUST1018,ORD05018,NaT,59361.98,North,active,na,31.0,Oct,Enterprise,Carol,USA
22,CUST1022,ORD05022,NaT,74798.34,North,active,follow up,56.0,Jul,Pro,Alice,USA
40,CUST1040,ORD05040,2025-08-01,46350.64,North,trial,NaN,48.0,Aug,Basic,David,USA
42,CUST1042,ORD05042,NaT,57019.82,North,active,follow up,51.0,Jul,Enterprise,Alice,Canada
44,CUST1044,ORD05044,NaT,63792.55,North,trial,follow up,26.0,Jan,Starter,Alice,UK
61,CUST1061,ORD05061,NaT,75656.23,North,active,NaN,27.0,Jun,Pro,Eve,USA
63,CUST1063,ORD05063,2025-02-23,27629.42,North,churned,-,53.0,Feb,Pro,Carol,USA
69,CUST1069,ORD05069,NaT,79326.02,North,inactive,-,46.0,Apr,Basic,David,USA
86,CUST1086,ORD05086,2025-10-11,70619.61,North,trial,na,36.0,Oct,Starter,Eve,USA
108,CUST1108,ORD05108,2025-11-09,44783.79,North,active,NaN,40.0,Nov,Pro,Alice,USA
154,CUST1154,ORD05154,NaT,77220.67,North,trial,follow up,56.0,Feb,Basic,Bob,USA
155,CUST1155,ORD05155,2025-09-11,34046.04,North,active,follow up,40.0,Sep,Enterprise,Carol,USA
158,CUST1158,ORD05158,2025-02-18,34370.41,North,trial,na,52.0,Feb,Basic,Carol,USA
163,CUST1163,ORD05163,2025-10-16,35603.38,North,trial,follow up,65.0,Oct,Enterprise,Bob,UK
166,CUST1166,ORD05166,2025-03-02,73194.22,North,churned,na,47.0,Mar,Basic,Eve,Canada
167,CUST1167,ORD05167,NaT,70073.96,North,inactive,NaN,39.0,May,Enterprise,Bob,USA
178,CUST1178,ORD05178,NaT,41762.73,North,inactive,NaN,55.0,Oct,Starter,Bob,USA
182,CUST1182,ORD05182,2025-01-17,73019.52,North,active,NaN,46.0,Jan,Basic,David,USA
185,CUST1185,ORD05185,NaT,46177.53,North,trial,NaN,27.0,Jul,Enterprise,Carol,UK
199,CUST1199,ORD05199,NaT,8749.15,North,active,NaN,41.0,Dec,Enterprise,Bob,USA
206,CUST1206,ORD05206,NaT,35071.85,North,trial,NaN,50.0,Sep,Pro,Alice,USA
216,CUST1216,ORD05216,NaT,74572.28,North,churned,na,27.0,Feb,Starter,David,USA
228,CUST1228,ORD05228,NaT,22719.25,North,active,NaN,NaN,Oct,Starter,Carol,USA
229,CUST1229,ORD05229,NaT,9195.47,North,trial,follow up,36.0,Oct,Enterprise,Bob,USA
235,CUST1235,ORD05235,NaT,7674.25,North,trial,NaN,47.0,Feb,Starter,Carol,USA
241,CUST1241,ORD05241,2025-03-07,55085.89,North,active,-,43.0,Mar,Basic,David,Canada
246,CUST1246,ORD05246,2025-07-01,67879.51,North,churned,NaN,59.0,Jul,Starter,Eve,USA
254,CUST1254,ORD05254,2025-12-18,49345.69,North,churned,follow up,26.0,Dec,Pro,Alice,USA
268,CUST1268,ORD05268,NaT,6044.63,North,trial,follow up,55.0,Dec,Starter,Alice,USA
271,CUST1271,ORD05271,NaT,18609.92,North,trial,-,35.0,Apr,Enterprise,David,USA
285,CUST1285,ORD05285,2025-11-01,53154.89,North,inactive,follow up,63.0,Nov,Basic,David,USA
290,CUST1290,ORD05290,NaT,30938.14,North,active,NaN,29.0,Dec,Starter,Carol,USA
306,CUST1306,ORD05306,NaT,80155.92,North,active,-,56.0,Dec,Basic,Bob,USA
320,CUST1320,ORD05320,NaT,12024.23,North,active,NaN,62.0,Jul,Starter,Alice,USA
326,CUST1326,ORD05326,NaT,73061.30,North,active,NaN,62.0,Mar,Enterprise,Eve,UK
334,CUST1334,ORD05334,2025-05-05,35220.98,North,trial,NaN,59.0,May,Enterprise,Bob,USA
338,CUST1338,ORD05338,NaT,51184.27,North,trial,na,27.0,Sep,Basic,Eve,Canada
340,CUST1340,ORD05340,NaT,65215.08,North,trial,na,56.0,Feb,Enterprise,Eve,UK
365,CUST1365,ORD05365,NaT,21405.01,North,churned,na,30.0,May,Pro,David,Canada
371,CUST1371,ORD05371,NaT,53122.69,North,active,NaN,NaN,Apr,Pro,Carol,USA
382,CUST1382,ORD05382,NaT,27759.70,North,trial,NaN,NaN,Nov,Starter,Alice,USA
399,CUST1399,ORD05399,NaT,69801.32,North,active,-,29.0,Jan,Starter,Bob,UK
400,CUST1400,ORD05400,NaT,22356.60,North,active,follow up,31.0,Sep,Enterprise,Carol,USA
408,CUST1408,ORD05408,NaT,26132.91,North,active,na,34.0,Nov,Pro,Eve,UK
412,CUST1412,ORD05412,NaT,33805.73,North,inactive,follow up,63.0,Oct,Basic,Alice,USA
417,CUST1417,ORD05417,2025-03-18,56230.31,North,churned,follow up,33.0,Mar,Basic,Carol,USA
428,CUST1428,ORD05428,NaT,39422.22,North,churned,follow up,48.0,Oct,Pro,Eve,UK
446,CUST1446,ORD05446,2025-05-31,11278.46,North,trial,follow up,57.0,May,Pro,Alice,USA
461,CUST1461,ORD05461,NaT,44884.83,North,active,NaN,40.0,Dec,Starter,Eve,USA
471,CUST1471,ORD05471,2025-01-09,69095.25,North,trial,follow up,43.0,Jan,Basic,Eve,USA
476,CUST1476,ORD05476,2025-07-12,53920.44,North,active,NaN,NaN,Jul,Pro,David,Canada
477,CUST1477,ORD05477,NaT,17920.54,North,active,na,48.0,Nov,Basic,Eve,USA
479,CUST1479,ORD05479,NaT,16869.25,North,churned,na,52.0,Mar,Pro,Bob,Canada
483,CUST1483,ORD05483,NaT,39179.05,North,active,na,39.0,Apr,Pro,Bob,USA
486,CUST1486,ORD05486,2025-08-02,76402.28,North,inactive,NaN,NaN,Aug,Basic,Alice,Canada
495,CUST1495,ORD05495,NaT,46251.25,North,active,follow up,50.0,Mar,Enterprise,Bob,UK
498,CUST1498,ORD05498,NaT,15317.86,North,active,NaN,31.0,Dec,Starter,David,USA

In [8]:
filtered_v2 = df.query("region == 'North' and rev_usd > 5000")
filtered_v2

,customer_id,order_id,order_date,rev_usd,region,status,notes,age,month,product,sales_rep,country
17,CUST1017,ORD05017,2025-05-02,82380.18,North,active,-,52.0,May,Basic,Carol,Canada
18,CUST1018,ORD05018,NaT,59361.98,North,active,na,31.0,Oct,Enterprise,Carol,USA
22,CUST1022,ORD05022,NaT,74798.34,North,active,follow up,56.0,Jul,Pro,Alice,USA
40,CUST1040,ORD05040,2025-08-01,46350.64,North,trial,NaN,48.0,Aug,Basic,David,USA
42,CUST1042,ORD05042,NaT,57019.82,North,active,follow up,51.0,Jul,Enterprise,Alice,Canada
44,CUST1044,ORD05044,NaT,63792.55,North,trial,follow up,26.0,Jan,Starter,Alice,UK
61,CUST1061,ORD05061,NaT,75656.23,North,active,NaN,27.0,Jun,Pro,Eve,USA
63,CUST1063,ORD05063,2025-02-23,27629.42,North,churned,-,53.0,Feb,Pro,Carol,USA
69,CUST1069,ORD05069,NaT,79326.02,North,inactive,-,46.0,Apr,Basic,David,USA
86,CUST1086,ORD05086,2025-10-11,70619.61,North,trial,na,36.0,Oct,Starter,Eve,USA
108,CUST1108,ORD05108,2025-11-09,44783.79,North,active,NaN,40.0,Nov,Pro,Alice,USA
154,CUST1154,ORD05154,NaT,77220.67,North,trial,follow up,56.0,Feb,Basic,Bob,USA
155,CUST1155,ORD05155,2025-09-11,34046.04,North,active,follow up,40.0,Sep,Enterprise,Carol,USA
158,CUST1158,ORD05158,2025-02-18,34370.41,North,trial,na,52.0,Feb,Basic,Carol,USA
163,CUST1163,ORD05163,2025-10-16,35603.38,North,trial,follow up,65.0,Oct,Enterprise,Bob,UK
166,CUST1166,ORD05166,2025-03-02,73194.22,North,churned,na,47.0,Mar,Basic,Eve,Canada
167,CUST1167,ORD05167,NaT,70073.96,North,inactive,NaN,39.0,May,Enterprise,Bob,USA
178,CUST1178,ORD05178,NaT,41762.73,North,inactive,NaN,55.0,Oct,Starter,Bob,USA
182,CUST1182,ORD05182,2025-01-17,73019.52,North,active,NaN,46.0,Jan,Basic,David,USA
185,CUST1185,ORD05185,NaT,46177.53,North,trial,NaN,27.0,Jul,Enterprise,Carol,UK
199,CUST1199,ORD05199,NaT,8749.15,North,active,NaN,41.0,Dec,Enterprise,Bob,USA
206,CUST1206,ORD05206,NaT,35071.85,North,trial,NaN,50.0,Sep,Pro,Alice,USA
216,CUST1216,ORD05216,NaT,74572.28,North,churned,na,27.0,Feb,Starter,David,USA
228,CUST1228,ORD05228,NaT,22719.25,North,active,NaN,NaN,Oct,Starter,Carol,USA
229,CUST1229,ORD05229,NaT,9195.47,North,trial,follow up,36.0,Oct,Enterprise,Bob,USA
235,CUST1235,ORD05235,NaT,7674.25,North,trial,NaN,47.0,Feb,Starter,Carol,USA
241,CUST1241,ORD05241,2025-03-07,55085.89,North,active,-,43.0,Mar,Basic,David,Canada
246,CUST1246,ORD05246,2025-07-01,67879.51,North,churned,NaN,59.0,Jul,Starter,Eve,USA
254,CUST1254,ORD05254,2025-12-18,49345.69,North,churned,follow up,26.0,Dec,Pro,Alice,USA
268,CUST1268,ORD05268,NaT,6044.63,North,trial,follow up,55.0,Dec,Starter,Alice,USA
271,CUST1271,ORD05271,NaT,18609.92,North,trial,-,35.0,Apr,Enterprise,David,USA
285,CUST1285,ORD05285,2025-11-01,53154.89,North,inactive,follow up,63.0,Nov,Basic,David,USA
290,CUST1290,ORD05290,NaT,30938.14,North,active,NaN,29.0,Dec,Starter,Carol,USA
306,CUST1306,ORD05306,NaT,80155.92,North,active,-,56.0,Dec,Basic,Bob,USA
320,CUST1320,ORD05320,NaT,12024.23,North,active,NaN,62.0,Jul,Starter,Alice,USA
326,CUST1326,ORD05326,NaT,73061.30,North,active,NaN,62.0,Mar,Enterprise,Eve,UK
334,CUST1334,ORD05334,2025-05-05,35220.98,North,trial,NaN,59.0,May,Enterprise,Bob,USA
338,CUST1338,ORD05338,NaT,51184.27,North,trial,na,27.0,Sep,Basic,Eve,Canada
340,CUST1340,ORD05340,NaT,65215.08,North,trial,na,56.0,Feb,Enterprise,Eve,UK
365,CUST1365,ORD05365,NaT,21405.01,North,churned,na,30.0,May,Pro,David,Canada
371,CUST1371,ORD05371,NaT,53122.69,North,active,NaN,NaN,Apr,Pro,Carol,USA
382,CUST1382,ORD05382,NaT,27759.70,North,trial,NaN,NaN,Nov,Starter,Alice,USA
399,CUST1399,ORD05399,NaT,69801.32,North,active,-,29.0,Jan,Starter,Bob,UK
400,CUST1400,ORD05400,NaT,22356.60,North,active,follow up,31.0,Sep,Enterprise,Carol,USA
408,CUST1408,ORD05408,NaT,26132.91,North,active,na,34.0,Nov,Pro,Eve,UK
412,CUST1412,ORD05412,NaT,33805.73,North,inactive,follow up,63.0,Oct,Basic,Alice,USA
417,CUST1417,ORD05417,2025-03-18,56230.31,North,churned,follow up,33.0,Mar,Basic,Carol,USA
428,CUST1428,ORD05428,NaT,39422.22,North,churned,follow up,48.0,Oct,Pro,Eve,UK
446,CUST1446,ORD05446,2025-05-31,11278.46,North,trial,follow up,57.0,May,Pro,Alice,USA
461,CUST1461,ORD05461,NaT,44884.83,North,active,NaN,40.0,Dec,Starter,Eve,USA
471,CUST1471,ORD05471,2025-01-09,69095.25,North,trial,follow up,43.0,Jan,Basic,Eve,USA
476,CUST1476,ORD05476,2025-07-12,53920.44,North,active,NaN,NaN,Jul,Pro,David,Canada
477,CUST1477,ORD05477,NaT,17920.54,North,active,na,48.0,Nov,Basic,Eve,USA
479,CUST1479,ORD05479,NaT,16869.25,North,churned,na,52.0,Mar,Pro,Bob,Canada
483,CUST1483,ORD05483,NaT,39179.05,North,active,na,39.0,Apr,Pro,Bob,USA
486,CUST1486,ORD05486,2025-08-02,76402.28,North,inactive,NaN,NaN,Aug,Basic,Alice,Canada
495,CUST1495,ORD05495,NaT,46251.25,North,active,follow up,50.0,Mar,Enterprise,Bob,UK
498,CUST1498,ORD05498,NaT,15317.86,North,active,NaN,31.0,Dec,Starter,David,USA

In [9]:
df[df['status'].isin(['active', 'trial'])]

,customer_id,order_id,order_date,rev_usd,region,status,notes,age,month,product,sales_rep,country
0,CUST1000,ORD05000,2025-05-21,2613.41,north,active,follow up,28.0,May,Basic,Alice,USA
1,CUST1001,ORD05001,2025-11-05,20159.85,West,active,follow up,63.0,Nov,Pro,Alice,USA
3,CUST1003,ORD05003,2025-07-13,82728.28,East,active,follow up,62.0,Jul,Enterprise,Alice,USA
5,CUST1005,ORD05005,2025-05-06,14961.22,South,trial,follow up,39.0,May,Enterprise,Bob,USA
7,CUST1007,ORD05007,NaT,21340.02,West,trial,NaN,59.0,Oct,Basic,Alice,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
495,CUST1495,ORD05495,NaT,46251.25,North,active,follow up,50.0,Mar,Enterprise,Bob,UK
496,CUST1496,ORD05496,NaT,35287.95,west,active,NaN,42.0,Jun,Starter,Carol,USA
497,CUST1497,ORD05497,NaT,19663.07,west,active,NaN,25.0,Jul,Starter,Eve,USA
498,CUST1498,ORD05498,NaT,15317.86,North,active,NaN,31.0,Dec,Starter,David,USA
499,CUST1499,ORD05499,2025-12-29,17835.63,NORTH,active,-,44.0,Dec,Enterprise,David,Canada

In [10]:
df['region'] = df['region'].str.strip().str.title()
df

,customer_id,order_id,order_date,rev_usd,region,status,notes,age,month,product,sales_rep,country
0,CUST1000,ORD05000,2025-05-21,2613.41,North,active,follow up,28.0,May,Basic,Alice,USA
1,CUST1001,ORD05001,2025-11-05,20159.85,West,active,follow up,63.0,Nov,Pro,Alice,USA
2,CUST1002,ORD05002,2025-03-21,29251.17,North,churned,-,43.0,Mar,Pro,Alice,Canada
3,CUST1003,ORD05003,2025-07-13,82728.28,East,active,follow up,62.0,Jul,Enterprise,Alice,USA
4,CUST1004,ORD05004,2025-04-30,83751.22,East,churned,follow up,51.0,Apr,Starter,Carol,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
495,CUST1495,ORD05495,NaT,46251.25,North,active,follow up,50.0,Mar,Enterprise,Bob,UK
496,CUST1496,ORD05496,NaT,35287.95,West,active,NaN,42.0,Jun,Starter,Carol,USA
497,CUST1497,ORD05497,NaT,19663.07,West,active,NaN,25.0,Jul,Starter,Eve,USA
498,CUST1498,ORD05498,NaT,15317.86,North,active,NaN,31.0,Dec,Starter,David,USA
499,CUST1499,ORD05499,2025-12-29,17835.63,North,active,-,44.0,Dec,Enterprise,David,Canada

In [12]:
print(df['customer_id'].isnull().sum())
df_dropped = df.dropna(subset=['customer_id'])
df_dropped

0

,customer_id,order_id,order_date,rev_usd,region,status,notes,age,month,product,sales_rep,country
0,CUST1000,ORD05000,2025-05-21,2613.41,North,active,follow up,28.0,May,Basic,Alice,USA
1,CUST1001,ORD05001,2025-11-05,20159.85,West,active,follow up,63.0,Nov,Pro,Alice,USA
2,CUST1002,ORD05002,2025-03-21,29251.17,North,churned,-,43.0,Mar,Pro,Alice,Canada
3,CUST1003,ORD05003,2025-07-13,82728.28,East,active,follow up,62.0,Jul,Enterprise,Alice,USA
4,CUST1004,ORD05004,2025-04-30,83751.22,East,churned,follow up,51.0,Apr,Starter,Carol,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
495,CUST1495,ORD05495,NaT,46251.25,North,active,follow up,50.0,Mar,Enterprise,Bob,UK
496,CUST1496,ORD05496,NaT,35287.95,West,active,NaN,42.0,Jun,Starter,Carol,USA
497,CUST1497,ORD05497,NaT,19663.07,West,active,NaN,25.0,Jul,Starter,Eve,USA
498,CUST1498,ORD05498,NaT,15317.86,North,active,NaN,31.0,Dec,Starter,David,USA
499,CUST1499,ORD05499,2025-12-29,17835.63,North,active,-,44.0,Dec,Enterprise,David,Canada

In [14]:
print(df.rev_usd.isnull().sum())
df_filled = df.fillna({'rev_usd': 0, 'notes': 'none'})
df_filled.rev_usd.isnull().sum()

29

np.int64(0)

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())

df_deduped = df.drop_duplicates(subset=['order_id'], keep='first')

df = df.rename(columns={
    'Customer ID ': 'customer_id',
    'Rev (USD)': 'revenue_usd'
})

In [15]:
revenue_by_region = df.groupby('region')['rev_usd'].sum()
revenue_by_region

region
East     2558663.31
North    7658481.14
South    5524752.31
West     4096587.28
Name: rev_usd, dtype: float64

In [22]:
region_summary = df.groupby('region').agg(
    total_revenue=('rev_usd', 'sum'),
    avg_order_value=('rev_usd', 'mean'),
    order_count=('order_id', 'count'),
    top_customer_revenue=('rev_usd', 'max')
).reset_index()
region_summary

  region  total_revenue  avg_order_value  order_count  top_customer_revenue
0   East     2558663.31     54439.644894           51              84805.88
1  North     7658481.14     41849.623716          195              84290.32
2  South     5524752.31     43847.240556          131              82957.02
3   West     4096587.28     35622.498087          123              84345.73

In [18]:
monthly_by_region = df.groupby(['region', 'month'])['rev_usd'].sum().reset_index()

monthly_by_region

   region month    rev_usd
0    East   Apr  121217.65
1    East   Aug  215385.07
2    East   Dec   37371.84
3    East   Feb  451338.41
4    East   Jan  182999.83
5    East   Jul  188116.96
6    East   Jun  203896.99
7    East   Mar  282047.61
8    East   May  332265.92
9    East   Nov  176942.80
10   East   Oct  157366.27
11   East   Sep  209713.96
12  North   Apr  539054.91
13  North   Aug  799982.29
14  North   Dec  489511.11
15  North   Feb  704080.72
16  North   Jan  653537.20
17  North   Jul  761621.16
18  North   Jun  773509.87
19  North   Mar  779324.71
20  North   May  727439.90
21  North   Nov  511539.88
22  North   Oct  542462.30
23  North   Sep  376417.09
24  South   Apr  483846.13
25  South   Aug  449752.87
26  South   Dec  361430.81
27  South   Feb  350466.36
28  South   Jan  568725.56
29  South   Jul  402984.67
30  South   Jun  590337.07
31  South   Mar  444284.48
32  South   May  557535.53
33  South   Nov  452356.44
34  South   Oct  584805.05
35  South   Sep  278227.34
36   West   Apr  293719.06
37   West   Aug  138271.54
38   West   Dec  172821.32
39   West   Feb  480438.80
40   West   Jan  370720.62
41   West   Jul  496495.57
42   West   Jun  514135.78
43   West   Mar  309578.38
44   West   May  308956.73
45   West   Nov  323432.47
46   West   Oct  353670.55
47   West   Sep  334346.46

In [20]:
pivot = df.pivot_table(
    values='rev_usd',
    index='region',
    columns='month',
    aggfunc='sum',
    fill_value=0
)
pivot

month,Apr,Aug,Dec,Feb,Jan,Jul,Jun,Mar,May,Nov,Oct,Sep
region,,,,,,,,,,,,
East,121217.65,215385.07,37371.84,451338.41,182999.83,188116.96,203896.99,282047.61,332265.92,176942.80,157366.27,209713.96
North,539054.91,799982.29,489511.11,704080.72,653537.20,761621.16,773509.87,779324.71,727439.90,511539.88,542462.30,376417.09
South,483846.13,449752.87,361430.81,350466.36,568725.56,402984.67,590337.07,444284.48,557535.53,452356.44,584805.05,278227.34
West,293719.06,138271.54,172821.32,480438.80,370720.62,496495.57,514135.78,309578.38,308956.73,323432.47,353670.55,334346.46